version: "3.8"

services:
  open-road-protocol-indexer:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DEPLOY_ENV: development
        BUILD_VERSION: local
    tty: true
    stdin_open: true
    ports:
      - "42069:42069"
    command: bash -c "npm run dev"

    environment:
      - NODE_ENV=development
      - DATABASE_SCHEMA=postgresql://orp_dev:orp_dev_pwd@dev-db:5432/orp_dev_db?schema=public
      - ALCHEMY_URL_BASE_SEPOLIA=${ALCHEMY_URL_BASE_SEPOLIA}

    depends_on:
      - dev-db

  dev-db:
    image: postgres:15-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=orp_dev
      - POSTGRES_PASSWORD=orp_dev_pwd
      - POSTGRES_DB=orp_dev_db
    volumes:
      - orp-dev-data:/var/lib/postgresql/data

  test:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DEPLOY_ENV: test
        BUILD_VERSION: local
    tty: true
    stdin_open: true
    ports:
      - "42069:42069"
    command: bash -c "while !</dev/tcp/test-db/5432; do sleep 1; done; make initdb && node_modules/.bin/vitest run"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=test
      - DATABASE_SCHEMA=postgresql://orp_test:orp_test_pwd@test-db:5432/orp_test_db?schema=public
      - ALCHEMY_URL_BASE_SEPOLIA=${ALCHEMY_URL_BASE_SEPOLIA}

    depends_on:
      - test-db

  test-db:
    image: postgres:15-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=orp_test
      - POSTGRES_PASSWORD=orp_test_pwd
      - POSTGRES_DB=orp_test_db

volumes:
  orp-dev-data: {}
