name: docker libraries scanning
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: docker libraries scanning
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{github.event.repository.name}}:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner in image mode
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{github.event.repository.name}}:${{ github.sha }}"
          trivy-config: trivy.yaml
